Redux toolkit
markgotit/bookshelf pull request #2
Opened 2021-07-22 11:23 UTC by markgotit

- Manage global state on store.
- Middleware logger, request use thunk.

2021-07-22 16:39 UTC, robertgotitapp requested changes
- Unit tests still failed

2021-07-22 16:39 UTC, robertgotitapp commented on src/app.js
> +  const {user} = useSelector(state => state.user)
Should get only token from the selector

2021-07-22 16:39 UTC, robertgotitapp commented on src/authenticated-app.js
> +  const {user} = useSelector(state => state.user)
Should get only username from the selector

2021-07-22 16:39 UTC, robertgotitapp commented on src/authenticated-app.js
> +  React.useEffect(() => {
import { useEffect } from React and utilize useEffect function directly

2021-07-22 16:39 UTC, robertgotitapp commented on src/components/book-row.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Should get listItem from the selector directly

2021-07-22 16:39 UTC, robertgotitapp commented on src/components/list-item-list.js
> +  const {listItems} = useSelector(state => state.books)
get listItems directly, do not need to use destructuring here

2021-07-22 16:39 UTC, robertgotitapp commented on src/components/rating.js
> +  const dispatchUpdateListItem = React.useCallback(
import { useState, useCallback } from React

2021-07-22 16:39 UTC, robertgotitapp commented on src/components/status-buttons.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
get listItem from selector directly

2021-07-22 16:39 UTC, robertgotitapp commented on src/context/auth-context.js
>    const token = user?.token
select token directly from redux

2021-07-22 16:39 UTC, robertgotitapp commented on src/components/rating.js
> +  const client = useClient()
Client is only used to pass to reducer slice. Should import in reducer slice directly rather than put it in the component

2021-07-22 16:39 UTC, robertgotitapp commented on src/authenticated-app.js
> +  const client = useClient()
Client is only used to pass to reducer slice. Should import in reducer slice directly rather than put it in the component

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client, query = ''}) => {
should not pass client as params

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client}) => {
should not pass client as params

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    return response
using async await is enough. Don't need to use .then here

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    const {update} = updates
Passing updates: { update : {}} is way too complicated

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client, bookId}) => {
don't need to pass client as param

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`newItem`, newItem)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        state.listItems.splice(index, 1)
Do not use mutable function

2021-07-22 16:39 UTC, robertgotitapp commented on src/features/user/userSlice.js
> +  status: 'idle',
Do you use this field anywhere?

2021-07-22 16:39 UTC, robertgotitapp commented on src/index.js
> +  console.log(`hi`)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/index.js
> +  console.log(`token`, token)
remove unnecessary log

2021-07-22 16:39 UTC, robertgotitapp commented on src/screens/book.js
> +  const listItem = listItems?.find(li => li.bookId === bookId) ?? null
Can select directly with selector

2021-07-22 16:39 UTC, robertgotitapp commented on src/screens/book.js
> +  let error = 'Co loi xay ra'
Use english please

2021-07-22 16:39 UTC, robertgotitapp commented on src/screens/discover.js
> +      dispatch(fetchBooksSearch({client, query}))
do not need to pass client as param

2021-07-22 16:39 UTC, robertgotitapp commented on src/screens/discover.js
> +      fetchBooksSearch({client, query: event.target.elements.search.value}),
do not need to pass client as param

2021-07-22 16:39 UTC, robertgotitapp commented on src/utils/hooks.js
> +      console.log(`promise`, typeof promise)
remove unnecessary log

2021-07-26 14:03 UTC, markgotit commented on src/authenticated-app.js
> +  React.useEffect(() => {
why not use React.useEffect() ?

2021-07-26 14:05 UTC, markgotit commented on src/authenticated-app.js
> +  const {user} = useSelector(state => state.user)
Done. Use selectorUser(user => user.token) export from userSlice.js

2021-07-26 14:07 UTC, markgotit commented on src/components/book-row.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Oke. I use custom hook useListItem(bookId)

2021-07-26 14:08 UTC, markgotit commented on src/components/list-item-list.js
> +  const {listItems} = useSelector(state => state.books)
Done.
export const selectorListItems = state => state.books.listItems

2021-07-26 14:22 UTC, markgotit commented on src/components/rating.js
> +  const dispatchUpdateListItem = React.useCallback(
why not use React.useEffect() ?

2021-07-26 14:24 UTC, markgotit commented on src/components/rating.js
> +  const client = useClient()
Done. I change use client from api.client.js

2021-07-26 14:26 UTC, markgotit commented on src/features/books/booksSlice.js
> +    const {update} = updates
Oke. 
Before, because createAsyncThunk only one params so i must change it to object. 
After, I don't pass client so update is one object. I used it.

2021-07-26 14:26 UTC, markgotit commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Done.

2021-07-26 14:27 UTC, markgotit commented on src/features/books/booksSlice.js
> +        state.listItems.splice(index, 1)
I can use it, it is syntax redux toolkit

2021-07-26 14:27 UTC, markgotit commented on src/screens/book.js
> +  let error = 'Co loi xay ra'
Done.

2021-07-28 01:09 UTC, robertgotitapp commented on src/authenticated-app.js
> +  React.useEffect(() => {
Because useEffect is shorter

2021-07-28 01:12 UTC, robertgotitapp commented on src/components/book-row.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Passing a param into selector would save space

2021-07-28 01:13 UTC, robertgotitapp commented on src/components/rating.js
> +  const dispatchUpdateListItem = React.useCallback(
Check the answer above

2021-07-28 07:48 UTC, markgotit commented on src/authenticated-app.js
> +  React.useEffect(() => {
I understand

2021-07-28 07:50 UTC, markgotit commented on src/components/book-row.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
You can see file src/app/hook.js, I don't quite understand.

2021-07-28 07:50 UTC, markgotit commented on src/components/rating.js
> +  const dispatchUpdateListItem = React.useCallback(
Done.

2021-07-28 07:50 UTC, markgotit commented on src/components/status-buttons.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Done. Check the answer above

2021-07-28 07:50 UTC, markgotit commented on src/context/auth-context.js
>    const token = user?.token
Done. Check the answer above

2021-07-28 07:50 UTC, markgotit commented on src/authenticated-app.js
> +  const client = useClient()
Done. Check the answer above

2021-07-28 07:50 UTC, markgotit commented on src/features/books/booksSlice.js
> +  async ({client, query = ''}) => {
Done. Check the answer above

2021-07-28 07:50 UTC, markgotit commented on src/features/books/booksSlice.js
> +  async ({client}) => {
Done. Check the answer above

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Done.

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Done

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +  async ({client, bookId}) => {
Done. Check the answer above

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Done

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Done

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Done

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +        console.log(`newItem`, newItem)
Done

2021-07-28 07:51 UTC, markgotit commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Done

2021-07-28 07:55 UTC, markgotit commented on src/features/user/userSlice.js
> +  status: 'idle',
I don't quite understand. Can you explain it to me ?

2021-07-28 07:55 UTC, markgotit commented on src/index.js
> +  console.log(`hi`)
Done

2021-07-28 07:55 UTC, markgotit commented on src/index.js
> +  console.log(`token`, token)
Done

2021-07-28 07:56 UTC, markgotit commented on src/screens/book.js
> +  const listItem = listItems?.find(li => li.bookId === bookId) ?? null
Done. Check the answer above

2021-07-28 07:56 UTC, markgotit commented on src/screens/discover.js
> +      dispatch(fetchBooksSearch({client, query}))
Done. Check the answer above

2021-07-28 07:56 UTC, markgotit commented on src/screens/discover.js
> +      fetchBooksSearch({client, query: event.target.elements.search.value}),
Done. Check the answer above

2021-07-28 07:56 UTC, markgotit commented on src/utils/hooks.js
> +      console.log(`promise`, typeof promise)
Done.

2021-07-30 08:17 UTC, markgotit commented
Project Redux.

2021-07-30 08:17 UTC, merged

2021-08-01 12:42 UTC, MinhNNguyen commented on src/app.js
> +  const {user} = useSelector(state => state.user)
Okay

2021-08-01 12:42 UTC, MinhNNguyen commented on src/authenticated-app.js
> +  const {user} = useSelector(state => state.user)
Okay

2021-08-01 13:10 UTC, robertgotitapp commented on src/app.js
> +  const {user} = useSelector(state => state.user)
Okay

2021-08-01 13:10 UTC, robertgotitapp commented on src/authenticated-app.js
> +  const {user} = useSelector(state => state.user)
Okay

2021-08-01 13:10 UTC, robertgotitapp commented on src/authenticated-app.js
> +  React.useEffect(() => {
Okay

2021-08-01 13:14 UTC, robertgotitapp commented on src/components/book-row.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Okay

2021-08-01 13:14 UTC, robertgotitapp commented on src/components/list-item-list.js
> +  const {listItems} = useSelector(state => state.books)
Okay

2021-08-01 13:14 UTC, robertgotitapp commented on src/components/rating.js
> +  const dispatchUpdateListItem = React.useCallback(
Okay

2021-08-01 13:14 UTC, robertgotitapp commented on src/components/status-buttons.js
> +  const listItem = listItems?.find(li => li.bookId === book.id) ?? null
Okay.

2021-08-01 13:14 UTC, robertgotitapp commented on src/context/auth-context.js
>    const token = user?.token
Okay.

2021-08-01 13:14 UTC, robertgotitapp commented on src/components/rating.js
> +  const client = useClient()
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/authenticated-app.js
> +  const client = useClient()
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client, query = ''}) => {
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client}) => {
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    return response
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    const {update} = updates
Okay.

2021-08-01 13:15 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +    console.log(`response`, response)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +  async ({client, bookId}) => {
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`newItem`, newItem)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        console.log(`action`, action)
Okay.

2021-08-01 13:16 UTC, robertgotitapp commented on src/features/books/booksSlice.js
> +        state.listItems.splice(index, 1)
Okay.

2021-08-01 13:21 UTC, robertgotitapp commented on src/index.js
> +  console.log(`hi`)
Okay

2021-08-01 13:21 UTC, robertgotitapp commented on src/index.js
> +  console.log(`token`, token)
Okay.

2021-08-01 13:21 UTC, robertgotitapp commented on src/screens/book.js
> +  const listItem = listItems?.find(li => li.bookId === bookId) ?? null
Okay.

2021-08-01 13:21 UTC, robertgotitapp commented on src/screens/book.js
> +  let error = 'Co loi xay ra'
Okay

2021-08-01 13:21 UTC, robertgotitapp commented on src/screens/discover.js
> +      dispatch(fetchBooksSearch({client, query}))
Okay

2021-08-01 13:22 UTC, robertgotitapp commented on src/screens/discover.js
> +      fetchBooksSearch({client, query: event.target.elements.search.value}),
Okay

2021-08-01 13:22 UTC, robertgotitapp commented on src/utils/hooks.js
> +      console.log(`promise`, typeof promise)
Okay